export const CURRENCY_CODES = {
  ALL: {symbol: 'Lek', country: 'Albania Lek'},
  AFN: {symbol: '؋', country: 'Afghanistan Afghani'},
  ARS: {symbol: '$', country: 'Argentina Peso'},
  AWG: {symbol: 'ƒ', country: 'Aruba Guilder'},
  AUD: {symbol: '$', country: 'Australia Dollar'},
  AZN: {symbol: '₼', country: 'Azerbaijan Manat'},
  BSD: {symbol: '$', country: 'Bahamas Dollar'},
  BBD: {symbol: '$', country: 'Barbados Dollar'},
  BYN: {symbol: 'Br', country: 'Belarus Ruble'},
  BZD: {symbol: 'BZ$', country: 'Belize Dollar'},
  BMD: {symbol: '$', country: 'Bermuda Dollar'},
  BOB: {symbol: '$b', country: 'Bolivia Bolíviano'},
  BAM: {symbol: 'KM', country: 'Bosnia and Herzegovina Convertible Mark'},
  BWP: {symbol: 'P', country: 'Botswana Pula'},
  BGN: {symbol: 'лв', country: 'Bulgaria Lev'},
  BRL: {symbol: 'R$', country: 'Brazil Real'},
  BND: {symbol: '$', country: 'Brunei Darussalam Dollar'},
  KHR: {symbol: '៛', country: 'Cambodia Riel'},
  CAD: {symbol: '$', country: 'Canada Dollar'},
  KYD: {symbol: '$', country: 'Cayman Islands Dollar'},
  CLP: {symbol: '$', country: 'Chile Peso'},
  CNY: {symbol: '¥', country: 'China Yuan Renminbi'},
  COP: {symbol: '$', country: 'Colombia Peso'},
  CRC: {symbol: '₡', country: 'Costa Rica Colon'},
  HRK: {symbol: 'kn', country: 'Croatia Kuna'},
  CUP: {symbol: '₱', country: 'Cuba Peso'},
  CZK: {symbol: 'Kč', country: 'Czech Republic Koruna'},
  DKK: {symbol: 'kr', country: 'Denmark Krone'},
  DOP: {symbol: 'RD$', country: 'Dominican Republic Peso'},
  XCD: {symbol: '$', country: 'East Caribbean Dollar'},
  EGP: {symbol: '£', country: 'Egypt Pound'},
  SVC: {symbol: '$', country: 'El Salvador Colon'},
  EUR: {symbol: '€', country: 'Euro Member Countries'},
  FKP: {symbol: '£', country: 'Falkland Islands (Malvinas) Pound'},
  FJD: {symbol: '$', country: 'Fiji Dollar'},
  GHS: {symbol: '¢', country: 'Ghana Cedi'},
  GIP: {symbol: '£', country: 'Gibraltar Pound'},
  GTQ: {symbol: 'Q', country: 'Guatemala Quetzal'},
  GGP: {symbol: '£', country: 'Guernsey Pound'},
  GYD: {symbol: '$', country: 'Guyana Dollar'},
  HNL: {symbol: 'L', country: 'Honduras Lempira'},
  HKD: {symbol: '$', country: 'Hong Kong Dollar'},
  HUF: {symbol: 'Ft', country: 'Hungary Forint'},
  ISK: {symbol: 'kr', country: 'Iceland Krona'},
  INR: {symbol: '', country: 'India Rupee'},
  IDR: {symbol: 'Rp', country: 'Indonesia Rupiah'},
  IRR: {symbol: '﷼', country: 'Iran Rial'},
  IMP: {symbol: '£', country: 'Isle of Man Pound'},
  ILS: {symbol: '₪', country: 'Israel Shekel'},
  JMD: {symbol: 'J$', country: 'Jamaica Dollar'},
  JPY: {symbol: '¥', country: 'Japan Yen'},
  JEP: {symbol: '£', country: 'Jersey Pound'},
  KZT: {symbol: 'лв', country: 'Kazakhstan Tenge'},
  KPW: {symbol: '₩', country: 'Korea (North) Won'},
  KRW: {symbol: '₩', country: 'Korea (South) Won'},
  KGS: {symbol: 'лв', country: 'Kyrgyzstan Som'},
  LAK: {symbol: '₭', country: 'Laos Kip'},
  LBP: {symbol: '£', country: 'Lebanon Pound'},
  LRD: {symbol:'$', country: 'Liberia Dollar'},
  MKD: {symbol:'ден', country: 'Macedonia Denar'},
  MYR: {symbol: 'RM', country: 'Malaysia Ringgit'},
  MUR: {symbol: '₨', country: 'Mauritius Rupee'},
  MXN: {symbol: '$', country: 'Mexico Peso'},
  MNT: {symbol: '₮', country: 'Mongolia Tughrik'},
  MZN: {symbol: 'MT', country: 'Mozambique Metical'},
  NAD: {symbol: '$', country: 'Namibia Dollar'},
  NPR: {symbol: '₨', country: 'Nepal Rupee'},
  ANG: {symbol: 'ƒ', country: 'Netherlands Antilles Guilder'},
  NZD: {symbol: '$', country: 'New Zealand Dollar'},
  NIO: {symbol: 'C$', country: 'Nicaragua Cordoba'},
  NGN: {symbol: '₦', country: 'Nigeria Naira'},
  NOK: {symbol: 'kr', country: 'Norway Krone'},
  OMR: {symbol: '﷼', country: 'Oman Rial'},
  PKR: {symbol: '₨', country: 'Pakistan Rupee'},
  PAB: {symbol: 'B/.', country: 'Panama Balboa'},
  PYG: {symbol: 'Gs', country: 'Paraguay Guarani'},
  PEN: {symbol: 'S/.', country: 'Peru Sol'},
  PHP: {symbol: '₱', country: 'Philippines Peso'},
  PLN: {symbol: 'zł', country: 'Poland Zloty'},
  QAR: {symbol: '﷼', country: 'Qatar Riyal'},
  RON: {symbol: 'lei', country: 'Romania Leu'},
  RUB: {symbol: '₽', country: 'Russia Ruble'},
  SHP: {symbol: '£', country: 'Saint Helena Pound'},
  SAR: {symbol: '﷼', country: 'Saudi Arabia Riyal'},
  RSD: {symbol: 'Дин.', country: 'Serbia Dinar'},
  SCR: {symbol: '₨', country: 'Seychelles Rupee'},
  SGD: {symbol: '$', country: 'Singapore Dollar'},
  SBD: {symbol: '$', country: 'Solomon Islands Dollar'},
  ZAR: {symbol: 'R', country: 'South Africa Rand'},
  LKR: {symbol: '₨', country: 'Sri Lanka Rupee'},
  SEK: {symbol: 'k', country: 'rSweden Krona'},
  CHF: {symbol: 'C', country: 'HFSwitzerland Franc'},
  SRD: {symbol: '$', country: 'Suriname Dollar'},
  SYP: {symbol: '£', country: 'Syria Pound'},
  TWD: {symbol: 'N', country: 'T$Taiwan New Dollar'},
  THB: {symbol: '฿', country: 'Thailand Baht'},
  TTD: {symbol: 'T', country: 'T$Trinidad and Tobago Dollar'},
  TRY: {symbol: '_', country: 'Turkey Lira'},
  TVD: {symbol: '$', country: 'Tuvalu Dollar'},
  UAH: {symbol: '₴', country: 'Ukraine Hryvnia'},
  GBP: {symbol: '£', country: 'United Kingdom Pound'},
  USD: {symbol: '$', country: 'United States Dollar'},
  UYU: {symbol: '$U', country: 'Uruguay Peso'},
  UZS: {symbol: 'лв', country: 'Uzbekistan Som'},
  VEF: {symbol: 'Bs', country: 'Venezuela Bolívar'},
  VND: {symbol: '₫', country: 'Viet Nam Dong'},
  YER: {symbol: '﷼', country: 'Yemen Rial'},
  ZWD: {symbol: 'Z$', country: 'Zimbabwe Dollar'},
};

export const Rules = {
  uppercase: v => {
    return v.toString().toUpperCase();
  },
  lowercase: v => {
    return v.toString().toLowerCase();
  },
  currency: (code = 'USD', codes = CURRENCY_CODES) => (v) => {
    if (codes.hasOwnProperty(code)) {
      v = codes[code].symbol + v.toString();
    }
    return v;
  }
};
